// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP8rJBUKJTuzsswaBRb3K9Az-6OorUSwo',
    appId: '1:783099808981:web:38588547276f04b739e65c',
    messagingSenderId: '783099808981',
    projectId: 'awesome-4b492',
    authDomain: 'awesome-4b492.firebaseapp.com',
    storageBucket: 'awesome-4b492.appspot.com',
    measurementId: 'G-TFV5WJJ2FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtklizTgXU15Tb1m4YYji6kdBqD3R-jT4',
    appId: '1:783099808981:android:059a54ace751f0b539e65c',
    messagingSenderId: '783099808981',
    projectId: 'awesome-4b492',
    storageBucket: 'awesome-4b492.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARfhwfeECAGaq_11OIr89QI6aLLJc82tY',
    appId: '1:783099808981:ios:1630b4e12f27319d39e65c',
    messagingSenderId: '783099808981',
    projectId: 'awesome-4b492',
    storageBucket: 'awesome-4b492.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARfhwfeECAGaq_11OIr89QI6aLLJc82tY',
    appId: '1:783099808981:ios:401a13befb96e16a39e65c',
    messagingSenderId: '783099808981',
    projectId: 'awesome-4b492',
    storageBucket: 'awesome-4b492.appspot.com',
    iosBundleId: 'com.example.testProject.RunnerTests',
  );
}
